name: "Build"

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        default: ""
        required: false
        options:
          - ""
          - consul
          - openbao
          - vault
      version:
        description: "The version of the software to build (e.g. 'latest' or '1.0.0')"
        required: false
        default: ""
      push:
        description: "Whether to allow pushing the built images to the registry (true/false)"
        required: false
        default: "false"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Generate matrix
        id: generate
        env:
          INPUT_TARGET: ${{ inputs.target }}
          INPUT_VERSION: ${{ inputs.version }}
        run: ./.github/scripts/generate-build-matrix.sh

  docker:
    needs:
      - prepare
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.prepare.outputs.matrix) }}
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/use-docker-buildx-bake.yml
    with:
      target: ${{ matrix.target }}
      version: ${{ matrix.version }}
      permit-login: ${{ inputs.push }}
      permit-push: ${{ inputs.push }}
      permit-cache: true
    secrets: inherit
